# Required
version: 2

# Default
formats: []

conda:
    environment: environment.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
#  builder: html
  configuration: docs/source/conf.py
#  fail_on_warning: true

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
  jobs:
    post_install:
       - echo "Commands ran at 'post_install' step"
       - /home/docs/checkouts/readthedocs.org/user_builds/sensortoolkit/checkouts/latest cat docs/conf.py
       - /home/docs/checkouts/readthedocs.org/user_builds/sensortoolkit/conda/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
       - /home/docs/checkouts/readthedocs.org/user_builds/sensortoolkit/conda/latest/bin/python -m sphinx -T -E -b readthedocssinglehtmllocalmedia -d _build/doctrees -D language=en . _build/localmedia
       - /home/docs/checkouts/readthedocs.org/user_builds/sensortoolkit/conda/latest/bin/python -m sphinx -b latex -D language=en -d _build/doctrees . _build/latex

## Optionally declare the Python requirements required to build your docs
#python:
#   version: 3.8
#   install:
#      - method: pip
#        path: .