# Required
version: 2

# Default
formats: []

#conda:
#    environment: environment.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
#   builder: html
   configuration: docs/conf.py
#  fail_on_warning: true

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
#    python: "miniconda3-4.7"

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .