# Generate a conda virtual environment for ReadtheDocs when building documentation. Currently not in use (2/6/23)

name: stk
channels:
  - defaults
dependencies:
  - sphinx==4.4.0
  - sphinxcontrib-htmlhelp
  - appdirs==1.4.4
  - python=3.8
  - requests==2.27.1
  - pip
  - pandas==1.3.5
  - statsmodels
  - numpy==1.21.2
  - setuptools==58.0.4
  - matplotlib==3.5.0
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-jsmath
  - sphinxcontrib-devhelp
  - pytz==2021.3
  - sphinxcontrib-applehelp
  - seaborn==0.11.2
  - chardet
  - tabulate
  - pathlib2
  - urllib3
  - scipy
  - pip:
    - timezonefinder==6.1.9
    - charset-normalizer==2.0.3
